version: "3.9"
services:
  dbt:
    image: fishtownanalytics/dbt:1.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
    working_dir: /app
    entrypoint:
      - /bin/bash
      - '-c'
    command:
      - dbt docs generate
      - dbt docs serve --no-browser
    environment:
      - DBT_PROFILES_DIR=.
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - 54322:5432
    entrypoint: /bin/bash
